from __future__ import annotations

import json
import os
import random
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import torch
from PIL import Image, UnidentifiedImageError
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.datasets import ImageFolder

from gcbm.imagenet_config import Config
from gcbm.imagenet_targets import (
    PREPROCESS_RESIZE_SIZE,
    PrecomputedTargetStore,
    build_gdino_target_sample,
    get_image_size,
)
from gcbm.target_batches import pad_sparse_targets


class SafeImageFolderWithAnnotations(Dataset):
    def __init__(
        self,
        root: str,
        annotation_dir: str,
        concepts: Sequence[str],
        input_size: int,
        min_image_bytes: int,
        split: str,
        manifest: str = "",
        train_random_transforms: bool = False,
    ) -> None:
        self.root = root
        self.annotation_dir = annotation_dir
        self.input_size = int(input_size)
        self.min_image_bytes = int(min_image_bytes)
        self.split = split
        self.train_random_transforms = bool(train_random_transforms)
        self.concepts = list(concepts)
        self.concept_to_idx = {name: idx for idx, name in enumerate(self.concepts)}
        self.sample_indices: Optional[List[int]] = None
        self.annotation_indices: Optional[List[int]] = None
        self.global_targets_only = False
        if manifest:
            self.dataset = self._load_manifest(manifest, split)
        else:
            self.dataset = ImageFolder(root=root, loader=self._safe_loader, transform=self._transform(split))
        self.precomputed_targets: Optional[PrecomputedTargetStore] = None

    def _load_manifest(self, manifest: str, split: str) -> Any:
        samples: List[Tuple[str, int]] = []
        sample_indices: List[int] = []
        annotation_indices: List[int] = []
        class_names: Dict[int, str] = {}
        with open(manifest, "r") as handle:
            for line_number, line in enumerate(handle, start=1):
                line = line.strip()
                if not line:
                    continue
                payload = json.loads(line)
                path = str(payload["path"])
                class_id = int(payload["class_id"])
                sample_index = int(payload.get("sample_index", len(samples)))
                annotation_index = int(payload.get("annotation_index", sample_index))
                samples.append((path, class_id))
                sample_indices.append(sample_index)
                annotation_indices.append(annotation_index)
                class_names[class_id] = str(payload.get("class_name", class_id))
        if not samples:
            raise ValueError(f"Manifest has no samples: {manifest}")
        max_class_id = max(class_names)
        classes = [str(idx) for idx in range(max_class_id + 1)]
        for class_id, class_name in class_names.items():
            classes[class_id] = class_name

        class ManifestDataset:
            def __len__(self) -> int:
                return len(self.samples)

        dataset = ManifestDataset()
        dataset.samples = samples
        dataset.classes = classes
        dataset.transform = self._transform(split)
        self.sample_indices = sample_indices
        self.annotation_indices = annotation_indices
        return dataset

    def attach_precomputed_targets(self, root: str, cfg: Optional[Config] = None, *, global_only: bool = False) -> None:
        """Attach on-disk GDINO supervision generated by precompute_target_store.

        The store is normally indexed by dataset position. Manifest subsets can
        also point into a larger precomputed store via sample_index.
        """
        if not root:
            return
        target_dir = Path(root) / self.split
        if not target_dir.is_dir():
            raise FileNotFoundError(f"Missing precomputed target directory: {target_dir}")
        self.precomputed_targets = PrecomputedTargetStore(target_dir)
        if self.sample_indices is None and len(self.precomputed_targets) != len(self.dataset):
            raise ValueError(
                f"Precomputed targets at {target_dir} have {len(self.precomputed_targets)} entries, "
                f"expected {len(self.dataset)}"
            )
        if self.sample_indices is not None:
            max_index = max(self.sample_indices) if self.sample_indices else -1
            if max_index >= len(self.precomputed_targets):
                raise ValueError(
                    f"Manifest references sample_index={max_index}, but precomputed targets at "
                    f"{target_dir} have only {len(self.precomputed_targets)} entries"
                )
        if self.precomputed_targets.n_concepts != len(self.concepts):
            raise ValueError(
                f"Precomputed targets at {target_dir} have {self.precomputed_targets.n_concepts} concepts, "
                f"expected {len(self.concepts)}"
            )
        if cfg is not None:
            self.precomputed_targets.validate_target_geometry(cfg)
        self.global_targets_only = bool(global_only)

    def apply_concept_filter(self, keep_indices: Sequence[int]) -> None:
        keep = [int(idx) for idx in keep_indices]
        self.concepts = [self.concepts[idx] for idx in keep]
        self.concept_to_idx = {name: idx for idx, name in enumerate(self.concepts)}
        if self.precomputed_targets is not None:
            self.precomputed_targets.set_concept_filter(keep)

    def _transform(self, split: str) -> transforms.Compose:
        normalize = transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225),
        )
        if split == "train" and self.train_random_transforms:
            return transforms.Compose(
                [
                    transforms.RandomResizedCrop(self.input_size),
                    transforms.RandomHorizontalFlip(),
                    transforms.ToTensor(),
                    normalize,
                ]
            )
        return transforms.Compose(
            [
                transforms.Resize(PREPROCESS_RESIZE_SIZE),
                transforms.CenterCrop(self.input_size),
                transforms.ToTensor(),
                normalize,
            ]
        )

    def _safe_loader(self, path: str) -> Image.Image:
        try:
            if os.path.getsize(path) < self.min_image_bytes:
                raise OSError(f"tiny file: {path}")
            with Image.open(path) as image:
                return image.convert("RGB")
        except (FileNotFoundError, OSError, UnidentifiedImageError):
            return Image.new("RGB", (self.input_size, self.input_size), color=0)

    def _annotation_path(self, sample_index: int) -> Path:
        split_dir = "imagenet_train" if self.split == "train" else "imagenet_val"
        return Path(self.annotation_dir) / split_dir / f"{sample_index}.json"

    def _load_annotation(self, sample_index: int) -> List[Dict[str, Any]]:
        path = self._annotation_path(sample_index)
        if not path.exists():
            return []
        try:
            with path.open("r") as handle:
                payload = json.load(handle)
        except Exception:
            return []
        if isinstance(payload, list):
            return payload
        return payload.get("concepts", [])

    def annotation_index_for_row(self, row_index: int) -> int:
        if self.annotation_indices is not None:
            return int(self.annotation_indices[row_index])
        if self.sample_indices is not None:
            return int(self.sample_indices[row_index])
        return int(row_index)

    def __len__(self) -> int:
        return len(self.dataset.samples)

    def __getitem__(self, index: int):
        path, class_id = self.dataset.samples[index]
        sample_index = int(self.sample_indices[index]) if self.sample_indices is not None else int(index)
        annotation_index = self.annotation_index_for_row(index)
        with self._safe_loader(path) as raw_image:
            image_size = (int(raw_image.size[0]), int(raw_image.size[1]))
            image = self.dataset.transform(raw_image) if self.dataset.transform is not None else raw_image
        item = {
            "image": image,
            "class_id": int(class_id),
            "sample_index": sample_index,
            "image_size": image_size,
        }
        if self.precomputed_targets is not None:
            if self.global_targets_only:
                item.update(self.precomputed_targets.get_global(sample_index))
            else:
                item.update(self.precomputed_targets.get(sample_index))
        else:
            item["annotation"] = self._load_annotation(annotation_index)
        return item


class DatasetView(Dataset):
    def __init__(self, base_dataset: SafeImageFolderWithAnnotations, indices: Sequence[int]) -> None:
        self.base_dataset = base_dataset
        self.indices = list(indices)
        self.concepts = base_dataset.concepts
        self.concept_to_idx = base_dataset.concept_to_idx

    def refresh_concepts(self) -> None:
        self.concepts = self.base_dataset.concepts
        self.concept_to_idx = self.base_dataset.concept_to_idx

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, index: int):
        return self.base_dataset[self.indices[index]]


def split_train_val(
    dataset: SafeImageFolderWithAnnotations,
    val_split: float,
    max_train_images: int,
    max_val_images: int,
    seed: int,
) -> Tuple[DatasetView, DatasetView]:
    total = len(dataset)
    indices = list(range(total))
    generator = random.Random(seed)
    indices = select_subset_indices(
        dataset,
        indices,
        max_images=max_train_images,
        seed=seed,
        stratify=True,
    )
    n_val = int(round(float(val_split) * len(indices)))
    n_val = min(max(n_val, 1), max(len(indices) - 1, 1))
    generator.shuffle(indices)
    val_indices = indices[:n_val]
    train_indices = indices[n_val:]
    if max_val_images > 0:
        val_indices = select_subset_indices(
            dataset,
            val_indices,
            max_images=max_val_images,
            seed=seed + 1,
            stratify=True,
        )
    return DatasetView(dataset, train_indices), DatasetView(dataset, val_indices)


def select_subset_indices(
    dataset: SafeImageFolderWithAnnotations,
    indices: Sequence[int],
    *,
    max_images: int,
    seed: int,
    stratify: bool,
) -> List[int]:
    selected = list(indices)
    if max_images <= 0 or len(selected) <= max_images:
        return selected

    generator = random.Random(seed)
    if not stratify:
        generator.shuffle(selected)
        return selected[:max_images]

    shuffled = list(selected)
    generator.shuffle(shuffled)
    class_to_indices: Dict[int, List[int]] = {}
    for sample_index in shuffled:
        _, class_id = dataset.dataset.samples[sample_index]
        class_to_indices.setdefault(int(class_id), []).append(int(sample_index))

    class_ids = list(class_to_indices)
    generator.shuffle(class_ids)
    per_class = max_images // len(class_ids)
    remainder = max_images % len(class_ids)

    chosen: List[int] = []
    chosen_set: set[int] = set()
    for class_position, class_id in enumerate(class_ids):
        want = per_class + (1 if class_position < remainder else 0)
        if want <= 0:
            continue
        class_choices = class_to_indices[class_id][:want]
        chosen.extend(class_choices)
        chosen_set.update(class_choices)

    if len(chosen) < max_images:
        for sample_index in shuffled:
            if sample_index in chosen_set:
                continue
            chosen.append(sample_index)
            chosen_set.add(sample_index)
            if len(chosen) >= max_images:
                break

    generator.shuffle(chosen)
    return chosen[:max_images]


def unwrap_dataset_view(dataset: Dataset) -> Tuple[SafeImageFolderWithAnnotations, List[int]]:
    if isinstance(dataset, DatasetView):
        return dataset.base_dataset, list(dataset.indices)
    if isinstance(dataset, SafeImageFolderWithAnnotations):
        return dataset, list(range(len(dataset)))
    raise TypeError(f"Unsupported dataset type for concept filtering: {type(dataset).__name__}")


def refresh_dataset_concepts(dataset: Dataset) -> None:
    if isinstance(dataset, DatasetView):
        dataset.refresh_concepts()


def count_concept_targets(dataset: Dataset, cfg: Config) -> Tuple[np.ndarray, int]:
    base_dataset, indices = unwrap_dataset_view(dataset)
    n_examples = len(indices)
    n_concepts = len(base_dataset.concepts)
    counts = np.zeros((n_concepts,), dtype=np.int64)
    if base_dataset.precomputed_targets is not None:
        targets = base_dataset.precomputed_targets.global_targets
        chunk_size = 4096
        for start in range(0, n_examples, chunk_size):
            chunk_indices = sorted(indices[start : start + chunk_size])
            counts += np.asarray(targets[chunk_indices], dtype=np.int64).sum(axis=0)
            if (start + len(chunk_indices)) % 50000 == 0:
                print(
                    f"[concept_filter] counted {start + len(chunk_indices)}/{n_examples} precomputed targets",
                    flush=True,
                )
        return counts, n_examples

    start_time = time.perf_counter()
    for position, sample_index in enumerate(indices, start=1):
        path, _ = base_dataset.dataset.samples[sample_index]
        annotation_index = base_dataset.annotation_index_for_row(sample_index)
        image_size = get_image_size(path, base_dataset.input_size, base_dataset.min_image_bytes)
        annotations = base_dataset._load_annotation(annotation_index)
        global_target, _, _ = build_gdino_target_sample(
            annotations,
            image_size,
            base_dataset.concept_to_idx,
            n_concepts,
            cfg,
        )
        counts += global_target.astype(np.int64, copy=False)
        if position % 50000 == 0:
            elapsed = time.perf_counter() - start_time
            print(
                f"[concept_filter] counted {position}/{n_examples} annotation targets "
                f"ips={position / max(elapsed, 1e-6):.2f}",
                flush=True,
            )
    return counts, n_examples


def apply_count_concept_filter(
    cfg: Config,
    train_dataset: Dataset,
    all_datasets: Sequence[Dataset],
) -> Optional[Dict[str, Any]]:
    if not cfg.filter_concepts_by_count:
        return None
    counts, n_examples = count_concept_targets(train_dataset, cfg)
    frequencies = counts.astype(np.float64) / max(int(n_examples), 1)
    keep_mask = (
        (counts >= int(cfg.concept_min_count))
        & (frequencies >= float(cfg.concept_min_frequency))
        & (frequencies <= float(cfg.concept_max_frequency))
    )
    keep_indices = np.flatnonzero(keep_mask).astype(np.int64)
    if keep_indices.size == 0:
        raise RuntimeError("Concept count filtering removed all concepts")

    seen: set[int] = set()
    for dataset in all_datasets:
        base_dataset, _ = unwrap_dataset_view(dataset)
        ident = id(base_dataset)
        if ident in seen:
            continue
        base_dataset.apply_concept_filter(keep_indices.tolist())
        seen.add(ident)
    for dataset in all_datasets:
        refresh_dataset_concepts(dataset)

    removed_indices = np.flatnonzero(~keep_mask).astype(np.int64)
    summary = {
        "enabled": True,
        "n_examples": int(n_examples),
        "original_n_concepts": int(counts.shape[0]),
        "kept_n_concepts": int(keep_indices.size),
        "removed_n_concepts": int(removed_indices.size),
        "min_count": int(cfg.concept_min_count),
        "min_frequency": float(cfg.concept_min_frequency),
        "max_frequency": float(cfg.concept_max_frequency),
        "keep_indices": keep_indices.tolist(),
        "removed_indices": removed_indices.tolist(),
        "kept_min_count": int(counts[keep_indices].min()),
        "kept_max_count": int(counts[keep_indices].max()),
    }
    print(
        "[concept_filter] kept "
        f"{summary['kept_n_concepts']}/{summary['original_n_concepts']} concepts "
        f"(removed {summary['removed_n_concepts']})",
        flush=True,
    )
    return summary


def collate_batch(batch: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    payload = {
        "images": torch.stack([item["image"] for item in batch], dim=0),
        "class_ids": torch.tensor([item["class_id"] for item in batch], dtype=torch.long),
        "sample_indices": torch.tensor([item["sample_index"] for item in batch], dtype=torch.long),
        "image_sizes": [item["image_size"] for item in batch],
    }
    if "global_target" not in batch[0]:
        payload["annotations"] = [item["annotation"] for item in batch]
        return payload

    payload["global_targets"] = torch.stack([item["global_target"] for item in batch], dim=0)
    if "mask_targets" not in batch[0]:
        return payload
    mask_h = int(batch[0]["mask_targets"].shape[-2])
    mask_w = int(batch[0]["mask_targets"].shape[-1])
    idx_pad, mask_pad, valid = pad_sparse_targets(
        [item["mask_indices"] for item in batch],
        [item["mask_targets"] for item in batch],
        mask_h=mask_h,
        mask_w=mask_w,
    )
    payload["mask_indices"] = idx_pad
    payload["mask_targets"] = mask_pad
    payload["mask_valid"] = valid
    return payload


def build_loader(
    dataset: Dataset,
    cfg: Config,
    shuffle: bool,
    drop_last: bool,
    *,
    batch_size: Optional[int] = None,
    workers: Optional[int] = None,
    pin_memory: Optional[bool] = None,
    persistent_workers: Optional[bool] = None,
    prefetch_factor: Optional[int] = None,
) -> DataLoader:
    effective_batch_size = int(cfg.batch_size if batch_size is None else batch_size)
    effective_workers = int(cfg.workers if workers is None else workers)
    effective_pin_memory = cfg.pin_memory if pin_memory is None else bool(pin_memory)
    kwargs: Dict[str, Any] = {
        "dataset": dataset,
        "batch_size": effective_batch_size,
        "shuffle": shuffle,
        "num_workers": effective_workers,
        "pin_memory": effective_pin_memory,
        "collate_fn": collate_batch,
        "drop_last": drop_last,
    }
    if effective_workers > 0:
        kwargs["persistent_workers"] = (
            cfg.persistent_workers if persistent_workers is None else bool(persistent_workers)
        )
        kwargs["prefetch_factor"] = max(
            1,
            int(cfg.prefetch_factor if prefetch_factor is None else prefetch_factor),
        )
    return DataLoader(**kwargs)
