dataset: chexpert
model_name: savlg_cbm
annotation_dir: /workspace/CHEX_CBM/gpt225_root
data_dir: /workspace/CHEXPERT_DATASET
img_root: /workspace/CHEXPERT_DATASET
train_csv: /workspace/CHEXPERT_DATASET/train.csv
val_csv: /workspace/CHEXPERT_DATASET/valid.csv
label_subset: all
uncertain_strategy: ones
frontal_only: true
concept_set: concept_files/chexpert_gpt225.txt
concept_file: concept_files/chexpert_gpt225.txt
precomputed_target_dir: /workspace/CHEX_CBM/precomputed_targets/chexpert_gpt225_thr070_softbox_mh14_mw14
backbone: densenet121
backbone_ckpt: /workspace/Medical_CBM/checkpoints/densenet121_full_finetune_feb8/best_model.pth
save_dir: /workspace/chexpert_full_runs/sgcbm_gpt225_precomputed_a100
activation_dir: /workspace/CHEX_CBM/saved_activations
max_train_images: 0
max_test_images: 0
lf_original_protocol: true
concept_threshold: 0.70
presence_mode: binary
min_concept_freq: 0.001
max_concept_freq: 0.95
target_mode: soft_box
savlg_target_mode: soft_box
mask_h: 14
mask_w: 14
cbl_batch_size: 256
cbl_epochs: 30
num_workers: 8
dense: false
saga_lam: 0.0007
saga_n_iters: 1000
saga_batch_size: 512
savlg_branch_arch: dual
savlg_spatial_stage: conv5
savlg_spatial_branch_mode: multiscale_conv45
savlg_residual_spatial_alpha: 0.2
disable_activation_cache: true
device: cuda
seed: 42
