dataset: chexpert
data_dir: /path/to/CHEXPERT_DATASET
concept_file: concept_files/chexpert_gpt225.txt
train_annotation_dir: /path/to/chexpert_train_annotations
val_annotation_dir: /path/to/chexpert_valid_annotations
save_dir: artifacts/medical
run_name: chexpert_sgcbm
label_subset: competition
backbone: densenet121
img_size: 224
mask_h: 14
mask_w: 14
target_mode: soft_box
concept_threshold: 0.15
neg_threshold: 0.02
loss_global_w: 1.0
loss_mask_w: 1.0
residual_alpha: 0.2
epochs: 10
batch_size: 64
final_batch_size: 256
num_workers: 8
threshold: 0.5
device: cuda
seed: 6885
