dataset: chexpert
model_name: vlg_cbm
data_dir: /workspace/CHEXPERT_DATASET
img_root: /workspace/CHEXPERT_DATASET
train_csv: /workspace/CHEXPERT_DATASET/train.csv
val_csv: /workspace/CHEXPERT_DATASET/valid.csv
concept_file: concept_files/chexpert_queries_520.txt
train_annotation_dir: /workspace/CHEX_CBM/annotations_queries520_train
val_annotation_dir: /workspace/CHEX_CBM/annotations_queries520_valid
train_presence_cache: /workspace/CHEX_CBM/annotations_queries520_train/presence_cache_191027_520_thr050.pt
val_presence_cache: /workspace/CHEX_CBM/annotations_queries520_valid/presence_cache_202_520_thr050.pt
save_dir: /workspace/chexpert_full_runs
run_name: chexpert_vlg_queries520_thr050_freq001_095_a100_full
label_subset: all
backbone: densenet121
backbone_ckpt: /workspace/Medical_CBM/checkpoints/densenet121_full_finetune_feb8/best_model.pth
concept_threshold: 0.50
presence_mode: binary
min_concept_freq: 0.001
max_concept_freq: 0.95
epochs: 30
early_stop_patience: 3
batch_size: 128
extract_batch_size: 256
extract_chunk_size: 10000
final_batch_size: 512
final_epochs: 1
use_saga: true
saga_lam: 0.0007
saga_iters: 500
saga_max_lr: 0.1
nec_values: 5,10,15,20,25,30
num_workers: 8
device: cuda
seed: 42
