dataset: chexpert
model_name: salf_cbm
data_dir: /workspace/CHEXPERT_DATASET
img_root: /workspace/CHEXPERT_DATASET
train_csv: /workspace/CHEXPERT_DATASET/train.csv
val_csv: /workspace/CHEXPERT_DATASET/valid.csv
label_subset: all
uncertain_strategy: ones
frontal_only: true
concept_set: /workspace/Medical_CBM/concepts/queries_520.txt
backbone: densenet121
backbone_ckpt: /workspace/Medical_CBM/checkpoints/densenet121_full_finetune_feb8/best_model.pth
lf_clip_name: cxrclip_swint_mcc
save_dir: /workspace/chexpert_full_runs
activation_dir: /workspace/CHEX_CBM/saved_activations
max_train_images: 0
max_test_images: 0
val_split: 0.10
lf_batch_size: 32
cbl_batch_size: 32
cbl_epochs: 20
clip_cutoff: 0.25
spatial_source: prompt_grid
grid_h: 7
grid_w: 7
prompt_radius: 3
spatial_batch_size: 8
prompt_batch_size: 256
cbl_type: mlp
cbl_hidden_layers: 1
cbl_use_batchnorm: true
dense: false
saga_lam: 0.002
saga_n_iters: 1000
saga_batch_size: 256
num_workers: 8
threshold: 0.5
device: cuda
seed: 42
